### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-inmasalcedo#1]
Good job @inmasalcedo !!!

Here you have some tips to improve the exercise:

- [x] Be extra careful with HTML syntax: meta info should be inside `head` tag and content inside `body` tag, first child of `ul` should be `li`
- [x] We need more semantic tags: main, nav, h1...
- [x] Avoid `br` tags to make the content jump when you can achieve it with CSS ;)
- [x] Where is the extension of the image file?
- [x]  Avoid uppercase on HTML, we can transform the text with CSS 
- [x] Improve hierarchy adding styles to body tag: `color`, `background-color`, `font-size`, `font-family`, `font-weight`.
- [x] When making the mobile version we do not need to give our boxes small fixed widths! We will work with media queries to make things change when needed ;)

Once you have these fixed try to finish the styles. 
Start with the mobile header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...)
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

**Comment by inmasalcedo** [comment]
Hi Nasi!!

Thanks for the feedback! I follow your tips and modify my project.
Let me know what do you think :)

**Comment by nasivuela** [comment]
Ole!!!

I have unchecked a point, try to add the body selector with some styles in CSS.

A final tip to make it an excellent work: 

- [ ] Indent your code to increase readability and avoid bugs.

**Comment by inmasalcedo** [comment]
Hi Nasi!

I add the main style features to the body and indented the code :) I add a README! I forgot it the first time! Let me know for further improvements!

**Comment by nasivuela** [comment]
You got it!

![](https://media.giphy.com/media/3o6wrw8nj9ZjKBW1ZS/giphy.gif)
